### ISSUE TITLE
[BUG] Strange `run.js` error when running `npx` commands

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/awesome-github-profiles#1662] opened 2023-01-16 03:53 UTC
### Description

When running `npx run format`, it seems to be checking for new `.gitignore` changes using the [`run.js`](https://github.com/DTRejo/run.js) package, which seems to be failing in various pull requests.

Seems that it probably must match the newest [`minimatch`](https://github.com/isaacs/minimatch) API or something like that. Not 100% sure what's the root cause and why that's happening.
A temporary fix would be to change the GitHub Actions workflow to run `npm run lint`, which doesn't show any errors.

**Comment by Pradumnasaraf** [comment] 2023-01-16 17:56
+1 to Dan.

Either they should run 

```bash
npm run format
```

Or

```
npx prettier --write <file name with path>
```

**Comment by Pradumnasaraf** [comment] 2023-01-16 18:04
The workflow is fixed now. It is working as intended. Thanks, Dan for pointing it out.

**Closed** 2023-01-16 18:08 UTC
Labels: bug
